package com.cmos.edccommon.service.impl.dept;

import com.alibaba.dubbo.config.annotation.Service;
import com.cmos.edccommon.beans.dept.Dept;
import com.cmos.edccommon.beans.dept.DeptExample;
import com.cmos.edccommon.dao.dept.DeptDAO;
import com.cmos.edccommon.iservice.dept.IDeptSV;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;

@Service(group = "edccommon")
public class DeptSVImpl implements IDeptSV {
    
    @Autowired
    private DeptDAO dao;
    
    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    public int countByExample(DeptExample example) {
    		return dao.countByExample(example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    public int deleteByExample(DeptExample example) {
    		return dao.deleteByExample(example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    public int deleteByPrimaryKey(Long parameterId) {
    		return dao.deleteByPrimaryKey(parameterId);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    public int save(Dept record) {
    		return dao.save(record);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    public int saveSelective(Dept record) {
    		return dao.saveSelective(record);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    public List<Dept> getByExample(DeptExample example) {
    		return dao.getByExample(example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    public Dept getByPrimaryKey(Long parameterId) {
    		return dao.getByPrimaryKey(parameterId);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    public int updateByExampleSelective(Dept record, DeptExample example) {
    		return dao.updateByExampleSelective(record, example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    public int updateByExample(Dept record, DeptExample example) {
    		return dao.updateByExample(record, example);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    public int updateByPrimaryKeySelective(Dept record) {
    		return dao.updateByPrimaryKeySelective(record);
    }

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    public Dept updateByPrimaryKey(Dept record) {
    	int count = dao.updateByPrimaryKey(record);
        if(count == 1) {
            return record;
        } else {
            return null;
        }
    }
}
