package com.cmos.edccommon.iservice.dept;

import com.cmos.edccommon.beans.dept.Dept;
import com.cmos.edccommon.beans.dept.DeptExample;

import java.util.List;

public interface IDeptSV {
    
    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    int countByExample(DeptExample example);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    int deleteByExample(DeptExample example);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    int deleteByPrimaryKey(Long parameterId);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    int save(Dept record);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    int saveSelective(Dept record);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    List<Dept> getByExample(DeptExample example);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    Dept getByPrimaryKey(Long parameterId);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    int updateByExampleSelective(Dept record, DeptExample example);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    int updateByExample(Dept record, DeptExample example);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    Dept updateByPrimaryKey(Dept record);
}
