package com.cmos.edccommon.iservice.emp;

import com.cmos.edccommon.beans.emp.Emp;
import com.cmos.edccommon.beans.emp.EmpExample;

import java.util.List;

/**
 * Demo示例,员工信息服务接口
 *
 * @author zhuanghd
 * @since 1.0
 */
public interface IEmpSV {

    /**
     * 分页查询
     * @param pageNum 页码
     * @param pageSize 每页的大小
     * @return 员工对象列表
     */
    List<Emp> getByPage(Integer pageNum, Integer pageSize);


    /**
     * 根据基本信息查询
     * @param ename 员工姓名
     * @param job 岗位
     * @param mgr 上级编号
     * @return 员工对象列表
     */
    List<Emp> getByBasicInfo(String ename, String job, Long mgr);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    int countByExample(EmpExample example);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    int deleteByExample(EmpExample example);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    int deleteByPrimaryKey(Long parameterId);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    int save(Emp record);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    int saveSelective(Emp record);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    List<Emp> getByExample(EmpExample example);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    Emp getByPrimaryKey(Long parameterId);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    int updateByExampleSelective(Emp record, EmpExample example);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    int updateByExample(Emp record, EmpExample example);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    int updateByPrimaryKeySelective(Emp record);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    Emp updateByPrimaryKey(Emp record);
}
